version: '3.7'
services:
  postgres:
    container_name: pg_test2
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_test
    ports:
      - '5438:5432'
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
